#!/usr/bin/env python3
import os
import sys
import signal

"""
This will be the interface to start and stop the daemon. Place in /usr/bin
"""

def start_daemon():
    print("Starting daemon")
    os.system("/var/adsyncd/adsyncd.py")
    if os.path.exists("/var/run/adsyncd.pid"):
        print("Daemon started successfully")
def stop_daemon():
    print("Stopping daemon")
    with open("/var/run/adsyncd.pid", "r") as lockfile:
        pid = int(lockfile.readline())
    os.kill(pid, signal.SIGTERM)
    if not os.path.exists("/var/run/lock/adsyncd.pid"):
        print("Daemon stopped successfully")

if os.getuid() != 0:
    print("This program must be run as root. Abotring.")
    sys.exit()
if sys.argv[1] == "start":
    start_daemon()
elif sys.argv[1] == "stop":
    stop_daemon()
else:
    print("Option not recognized. Usage: adsync start or adsync stop")